"""English translations: `harvest --source` and `--author-email`, the identity hints, the roster flags."""

MESSAGES = {
    '从哪里取论文：pubmed（默认，生物医学）、openalex（全学科——工科、计算机、物理、化学、社科的导师用这个）或 both（两边都取再去重合并）。openalex 和 both 会先按姓名+机构在 OpenAlex 里找作者，候选不止一位时列出来让你认': 'Where to take papers from: pubmed (the default, biomedicine), openalex (every field — use this for an advisor in engineering, computer science, physics, chemistry or the social sciences) or both (take both and deduplicate). openalex and both first look the author up in OpenAlex by name and institution, and list the candidates for you to pick when there is more than one',
    '名单文件里没有「导出日期」列时，给整份文件填上导出的那一天。文件里有这一列时以文件为准': 'When the roster file has no 导出日期 (export date) column, the day it was exported, for the whole file. A column in the file wins',
    '名单文件里没有「库来源」列时，给整份文件填上它来自哪个库（CNKI、万方 或 其他）。从知网/万方直接导出的文件都没有这一列': 'When the roster file has no 库来源 (source library) column, the library it came from, for the whole file (CNKI, 万方 or 其他). A file exported straight from CNKI or 万方 never has this column',
    '导师本人的邮箱（课题组主页上那个），可重复给。整个地址精确匹配，没有 ORCID 时这是最强的证据——常见姓名下同一所学校里也几乎不会撞上': "The advisor's own email address (the one on the lab page); may be repeated. Matched as a whole address, it is the strongest evidence there is without an ORCID — under a common name, even at one university, almost nobody else shares it",
    '  候选 %d/%d: %s | ID=%s | ORCID=%s | 作品数=%s | 被引=%s | 机构: %s | 方向: %s': '  candidate %d/%d: %s | ID=%s | ORCID=%s | works=%s | citations=%s | institutions: %s | topics: %s',
    '  单位 %s（%d 条）': '  department %s (%d records)',
    '  邮箱 %s（%d 条）': '  email %s (%d records)',
    '--source openalex 需要一位确定的 OpenAlex 作者，本次没有定下来（候选为多个、为零，或查询失败，见上）。认出是哪一位后加 --openalex-author-id <ID> 重跑。': '--source openalex needs one definite OpenAlex author, and none was settled this time (several candidates, none, or a failed lookup — see above). Once you recognise which one it is, re-run with --openalex-author-id <ID>.',
    '--source openalex：不查 PubMed，语料全部来自 OpenAlex 作者 %s 名下的作品。': '--source openalex: PubMed is not searched; the whole corpus comes from the works filed under OpenAlex author %s.',
    'OpenAlex 作者消歧只返回一个候选并已自动采纳：%s (%s)，ORCID=%s，作品数=%s，机构=%s，方向=%s。**这不是确认**——检索用的是 display_name.search 模糊匹配，唯一候选完全可能是同名的另一个人，也可能是本人被拆成多个 profile 后只命中了其中一个。请照上面的机构和作品数核对一眼；不对就加 --openalex-author-id <正确的 ID> 重跑。': 'OpenAlex author disambiguation returned a single candidate and adopted it automatically: %s (%s), ORCID=%s, works=%s, institutions=%s, topics=%s. **This is not a confirmation** — the search is a display_name.search fuzzy match, and the single candidate may well be another person with the same name, or this person split across several profiles with only one of them matched. Check the institutions and works count above; if they are wrong, re-run with --openalex-author-id <correct ID>.',
    'PubMed 只收生物医学和生命科学。导师在工科、计算机、物理、化学或社科的话，改用 --source openalex 从 OpenAlex（覆盖全学科）取论文。': 'PubMed covers biomedicine and the life sciences only. For an advisor in engineering, computer science, physics, chemistry or the social sciences, use --source openalex to take papers from OpenAlex, which covers every field.',
    'PubMed 里这个名字没有记录，语料只用 OpenAlex 名下的作品。': 'PubMed has no records under this name; the corpus uses only the works filed in OpenAlex.',
    '这 %d 条记录里，「%s」坐在第一/末位/通讯位时，旁边印着下面这些邮箱和单位——同名的不同的人会在这里分开。认出导师的那一个，加 --author-email <邮箱> 或 --affiliation-keyword "<单位>" 重跑，再加 --require-affiliation 把对不上的同名记录挡在语料外：': 'In these %d records, "%s" in a first, last or corresponding slot is printed beside the emails and departments below — different people sharing the name separate here. Recognise the advisor\'s, re-run with --author-email <email> or --affiliation-keyword "<department>", and add --require-affiliation to keep the namesakes\' records out of the corpus:',
    '这次没有取到任何可用的论文（PubMed 为零，OpenAlex 也没有本人在第一/末位/通讯位的作品），不写语料文件。': 'No usable paper this time (nothing from PubMed, and no OpenAlex work with this author in a first, last or corresponding slot), so no corpus file is written.',
}
